export const localStorageKey = {
  // common
  chatMode: 'chatMode',
  api: 'api',
  localLanguage: 'localLanguage',
  replyLanguage: 'replyLanguage',
  insertType: 'insertType',
  useWordFormatting: 'useWordFormatting',
  useSelectedText: 'useSelectedText',
  agentMaxIterations: 'agentMaxIterations',
  threadId: 'threadId',
  // official api
  apiKey: 'apiKey',
  model: 'model',
  customModel: 'customModel',
  customModels: 'customModels',
  temperature: 'temperature',
  maxTokens: 'maxTokens',
  basePath: 'basePath',
  // azure api
  azureAPIKey: 'azureAPIKey',
  azureAPIEndpoint: 'azureAPIEndpoint',
  azureDeploymentName: 'azureDeploymentName',
  azureMaxTokens: 'azureMaxTokens',
  azureTemperature: 'azureTemperature',
  azureAPIVersion: 'azureAPIVersion',
  // gemini api
  geminiAPIKey: 'geminiAPIKey',
  geminiMaxTokens: 'geminiMaxTokens',
  geminiTemperature: 'geminiTemperature',
  geminiModel: 'geminiModel',
  geminiCustomModel: 'geminiCustomModel',
  geminiCustomModels: 'geminiCustomModels',
  // ollama api
  ollamaEndpoint: 'ollamaEndpoint',
  ollamaModel: 'ollamaModel',
  ollamaTemperature: 'ollamaTemperature',
  ollamaCustomModel: 'ollamaCustomModel',
  ollamaCustomModels: 'ollamaCustomModels',
  // groq api
  groqAPIKey: 'groqAPIKey',
  groqTemperature: 'groqTemperature',
  groqMaxTokens: 'groqMaxTokens',
  groqModel: 'groqModel',
  groqCustomModel: 'groqCustomModel',
  groqCustomModels: 'groqCustomModels',
  // proxy
  enableProxy: 'enableProxy',
  proxy: 'proxy',
  defaultSystemPrompt: 'defaultSystemPrompt',
  defaultPrompt: 'defaultPrompt',
} as const
